### PR TITLE
Fix: Rebrand Truffle Example Readmes and packages

### PR DESCRIPTION
**Pull request by riccardopersiani**
Please @D-Nice, could you review the changes?

### CODE REVIEW

**Comment by D-Nice** [comment]
depends on https://github.com/provable-things/ethereum-examples/pull/59

**Comment by D-Nice** [comment]
changes look good to me, but waiting on dependent PR inclusion first.

**Comment by riccardopersiani** [comment]
@D-Nice update with code rebrand.

Every example was successfully tested.

Please rerun test on you local machine.

**Comment by D-Nice** [comment]
CI live and was all green on branch (needed restart on one of tests one time due to some truffle/migration issue).

**Comment by D-Nice** [comment]
will do manual review tomorrow of this PR.

**Comment by D-Nice** [comment]
it seems parallelization with the random example isn't a great idea and can cause deployment/nonce issues, one archaic fix would be to add a random start delay.

**Pull request merged**
